name: CI

on:
  push:
    branches: source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run GitSubtree
      run: |
        echo GitSubtree
        git subtree push --prefix docs/ origin master
